djLeeeee/project1

plans/forms.py
plans/templates/plans/index.html
templates/base.html

index 페이지에 약속 날짜 별로 조회 기능 추가

---

plans/templates/plans/plan_update.html

update.html에서 pk 넘겨주는것을 누락해서 수정

Modify plan_update.html

---

meeting/settings.py
static/base.css
templates/base.html

navbar 대충 다듬어 봤는데, 추가 기능이 아직 안 들어가서 딱히 넣을 게 없더라

polish navbar

---

accounts/static/accounts/signup.css
accounts/templates/accounts/signup.html
accounts/views.py
static/base.css
templates/base.html

create signup page

---

accounts/templates/accounts/login.html
accounts/urls.py
accounts/views.py
plans/views.py
templates/base.html

로그인 로그아웃 기능 추가
+ `next` 키워드로 `redirect`가 안 되던 문제 수정
+ `login_required` 데코레이터 추가

로그인, 로그아웃 추가

---

accounts/static/accounts/login.css
accounts/templates/accounts/login.html
accounts/templates/accounts/signup.html
plans/templates/plans/plan_create.html

doing work in plan_create

---

plans/templates/plans/plan_detail.html

참석 인원 비로그인이어도 보이도록 수정

---

meeting/settings.py
plans/forms.py
plans/static/plans/plan_detail.css
plans/templates/plans/plan_detail.html
requirements.txt
templates/base.html

detail 페이지 꾸미기, fontawesome 추가

---

plans/static/plans/index.css
static/base.css
templates/base.html

navbar 레이아웃 완성

---

plans/templates/plans/plan_detail.html
static/base.css
templates/base.html

navbar width:1000
content width:950

base.html 수정 + 댓글 collapse

---

plans/static/plans/index.css

index.html 수정

---

plans/templates/plans/plan_detail.html

1. 참석/명단/댓글 버튼 그룹으로 묶기
2. collapse로 참석자 명단 / 댓글 나오게 하기
3. 댓글 숫자 표시하기
4. 로그인 안 한 유저에게는 참석/취소 버튼 뜨지 않게 하기
저질러버렸다!

detail 페이지 수정

---

plans/templates/plans/index.html
plans/views.py

기존 `filter` 후 `for` 문과 `if` 문 탐색으로 구현한 방법을 `filter` 한 번으로 해결할 수 있도록 변경.

약속 있는 날짜 조회/신규 약속 표시 로직 변경

---

accounts/templates/accounts/my_page.html
accounts/urls.py
accounts/views.py
plans/templates/plans/plan_detail.html
plans/urls.py
plans/views.py
templates/base.html

* plan_delete 생성
* my_page 작성
* 작성 게시글 조회
* 참석버튼을 누른 미래의 약속
* 참석버튼을 누른 과거의 약속

plan_delete, my_page 포맷 생성

---

accounts/static/accounts/login.css
accounts/static/accounts/signup.css
plans/static/plans/index.css
plans/static/plans/plan_create.css
plans/templates/plans/index.html
plans/templates/plans/plan_create.html
plans/templates/plans/plan_date.html
static/base.css
templates/base.html

index 화면 재구성(중앙부터 표시되게)
전체적인 레이아웃 게시판처럼 바꿈
너무 번쩍번쩍하면 다시 수정하죠

hi username 클릭 시 마이페이지

---

plans/templates/plans/index.html
plans/views.py

어노테이트, 딕셔너리 가지고 씨름하지 않아도 됐다.
template에서 date에 요일 필터 먹여주면 해결!

필터로 요일 표시 해결

---

accounts/static/accounts/my_page.css
accounts/templates/accounts/my_page.html

다시할겁니다... details를 써보려고 시도만 해봤어요

my_page html 수정

---

accounts/static/accounts/my_page.css
accounts/templates/accounts/my_page.html

my_page 수정

---

plans/static/plans/plan_coming.css
plans/templates/plans/index.html
plans/templates/plans/plan_coming.html
plans/urls.py
plans/views.py
static/base.css

make plan_coming.html

---

plans/views.py

약속을 만들 때 자동으로 참석 신청을 하게 만듦

---

plans/forms.py
templates/base.html

피드백 반영하여 일부 수정했습니다.
변경사항
1. title을 THUNDERMAN으로 변경
2. 댓글 placeholder를 '댓글을 작성해주세요' 로 변경
진행 중 사항
1. placeholder를 경우에 따라 다르게 만들어 보려고 했는데 아직 해결법을 못 찾았습니다.
2. 댓글 창이 기본적으로 열려있도록 변경하려 했으나 해결법을 못 찾았습니다.
data-bs-toggle = 'collapse in', 
data-bs-toggle = 'collapse show',
aria-expanded="true"
등 수정해봤는데 작동 안함

title 및 댓글 placeholder 변경

---

plans/static/plans/plan_detail.css
plans/templates/plans/plan_detail.html

Cr mo marco 3000

---

plans/templates/plans/plan_detail.html

make plan_detail description tag break line

---

accounts/static/accounts/my_page.css
accounts/templates/accounts/my_page.html

* 당일 약속 남은시간 출력 
* css, html 변경

modify my_page
